#!/bin/sh

cd /etc/share/zeronet

# Hack to ensure that the file access port is opened
# This is because zeronet normally relies on an internet site
# to do this, but on a purely local mesh the internet isn't available
sed -i 's|fileserver_port = 0|fileserver_port = config.fileserver_port\n            sys.modules["main"].file_server.port_opened = True|g' /etc/share/zeronet/src/Site/Site.py

/usr/bin/python zeronet.py --ip_external $(hostname).local --trackers_file /etc/share/zeronet/bootstrap
