#!/bin/sh

cd /etc/share/zeronet

if [ ! -d /etc/tor ]; then
    /usr/bin/python zeronet.py --ip_external $(hostname).local --trackers_file /etc/share/zeronet/bootstrap
else
    /usr/bin/python zeronet.py --tor always --ip_external $(hostname).local --trackers_file /etc/share/zeronet/bootstrap
fi
