#!/bin/bash

set -e

APP='zeronet'

if [ ! -d /etc/share/${APP} ]; then
    mkdir /etc/share/${APP}
fi

pip install msgpack-python --upgrade

if ! id -u "${APP}" >/dev/null 2>&1; then
    useradd -d /etc/share/${APP}/ -s /bin/false ${APP}
fi

if [ ! -f /etc/systemd/system/multi-user.target.wants/${APP}.service ]; then
    ln -s /lib/systemd/system/${APP}.service /etc/systemd/system/multi-user.target.wants/${APP}.service
fi

if [ ! -f /etc/systemd/system/multi-user.target.wants/${APP}-mesh.service ]; then
    ln -s /lib/systemd/system/${APP}-mesh.service /etc/systemd/system/multi-user.target.wants/${APP}-mesh.service
fi

if [ ! -f /etc/share/${APP}/data ]; then
    ln -s /var/lib/${APP} /etc/share/${APP}/data
fi

if [ ! -f /etc/share/${APP}/bootstrap ]; then
    ln -s /var/lib/${APP}/bootstrap /etc/share/${APP}/bootstrap
fi

chown -R ${APP}:${APP} /etc/share/${APP}

exit 0
