#!/bin/bash

set -e

pip install msgpack-python --upgrade

if ! id -u "zeronet" >/dev/null 2>&1; then
	useradd -d /etc/share/zeronet/ -s /bin/false zeronet
fi
chown -R zeronet:zeronet /etc/share/zeronet

if ! id -u "tracker" >/dev/null 2>&1; then
	useradd -d /etc/share/tracker/ -s /bin/false tracker
fi
if [ ! -d /etc/share/tracker ]; then
    mkdir /etc/share/tracker
fi

chown -R tracker:tracker /etc/share/tracker

if [ ! -f /etc/systemd/system/multi-user.target.wants/tracker.service ]; then
    ln -s /lib/systemd/system/tracker.service /etc/systemd/system/multi-user.target.wants/tracker.service
fi

if [ ! -f /etc/systemd/system/multi-user.target.wants/zeronet.service ]; then
    ln -s /lib/systemd/system/zeronet.service /etc/systemd/system/multi-user.target.wants/zeronet.service
fi

exit 0
